In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("E:\\DATA SCIENCE\\NUMPY-PANDAS\\DATASETS\\dirty_cafe_sales.csv")

In [3]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [4]:
df.rename(columns={'Price Per Unit':'Price_Per_Unit','Total Spent':'Total_Spent','Transaction Date':'Transaction_Date','Payment Method':'Payment_Method','Transaction ID':'Transaction_ID'},inplace=True)

In [5]:
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [6]:
df1=df.drop(columns=['Transaction_ID','Payment_Method','Location','Transaction_Date'])

In [7]:
df1

          Item Quantity Price_Per_Unit Total_Spent
0       Coffee        2            2.0         4.0
1         Cake        4            3.0        12.0
2       Cookie        4            1.0       ERROR
3        Salad        2            5.0        10.0
4       Coffee        2            2.0         4.0
...        ...      ...            ...         ...
9995    Coffee        2            2.0         4.0
9996       NaN        3            NaN         3.0
9997    Coffee        4            2.0         8.0
9998    Cookie        3            NaN         3.0
9999  Sandwich        3            4.0        12.0

[10000 rows x 4 columns]

In [8]:
df1.dtypes

Item              object
Quantity          object
Price_Per_Unit    object
Total_Spent       object
dtype: object

In [9]:
df1.Quantity.unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [10]:
df1.Item.unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [11]:
df1.head(9)

       Item Quantity Price_Per_Unit Total_Spent
0    Coffee        2            2.0         4.0
1      Cake        4            3.0        12.0
2    Cookie        4            1.0       ERROR
3     Salad        2            5.0        10.0
4    Coffee        2            2.0         4.0
5  Smoothie        5            4.0        20.0
6   UNKNOWN        3            3.0         9.0
7  Sandwich        4            4.0        16.0
8       NaN        5            3.0        15.0

In [12]:
df1['Price_Per_Unit'].replace(['UNKNOWN','ERROR'], np.nan, inplace=True)

In [13]:
df1.Price_Per_Unit.unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan], dtype=object)

In [14]:
df1['Quantity'].replace(['UNKNOWN','ERROR'], np.nan, inplace=True)

In [15]:
df1.Quantity.unique()

array(['2', '4', '5', '3', '1', nan], dtype=object)

In [16]:
df1.Total_Spent.unique()

array(['4.0', '12.0', 'ERROR', '10.0', '20.0', '9.0', '16.0', '15.0',
       '25.0', '8.0', '5.0', '3.0', '6.0', nan, 'UNKNOWN', '2.0', '1.0',
       '7.5', '4.5', '1.5'], dtype=object)

In [17]:
df1['Total_Spent'].replace(['UNKNOWN','ERROR'], np.nan, inplace=True)

In [18]:
df1.Total_Spent.unique()

array(['4.0', '12.0', nan, '10.0', '20.0', '9.0', '16.0', '15.0', '25.0',
       '8.0', '5.0', '3.0', '6.0', '2.0', '1.0', '7.5', '4.5', '1.5'],
      dtype=object)

In [19]:
df1

          Item Quantity Price_Per_Unit Total_Spent
0       Coffee        2            2.0         4.0
1         Cake        4            3.0        12.0
2       Cookie        4            1.0         NaN
3        Salad        2            5.0        10.0
4       Coffee        2            2.0         4.0
...        ...      ...            ...         ...
9995    Coffee        2            2.0         4.0
9996       NaN        3            NaN         3.0
9997    Coffee        4            2.0         8.0
9998    Cookie        3            NaN         3.0
9999  Sandwich        3            4.0        12.0

[10000 rows x 4 columns]

In [20]:
df1.dtypes

Item              object
Quantity          object
Price_Per_Unit    object
Total_Spent       object
dtype: object

In [21]:
def datatype(x):
    return float(x)
a='10'
datatype(a)

10.0

In [22]:
df1['Price_Per_Unit']=df1.Price_Per_Unit.apply(datatype)

In [23]:
df1.Price_Per_Unit.unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [24]:
df1['Quantity']=df1.Quantity.apply(datatype)

In [25]:
df1.Quantity.unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [26]:
df1['Total_Spent']=df1.Total_Spent.apply(datatype)

In [27]:
df1.Total_Spent.unique()

array([ 4. , 12. ,  nan, 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,
        3. ,  6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

In [28]:
df1.dtypes

Item               object
Quantity          float64
Price_Per_Unit    float64
Total_Spent       float64
dtype: object

In [29]:
df1['new_price']=df1['Total_Spent']/df1['Quantity']

In [30]:
df1['new_price']

0       2.0
1       3.0
2       NaN
3       5.0
4       2.0
       ...
9995    2.0
9996    1.0
9997    2.0
9998    1.0
9999    4.0
Name: new_price, Length: 10000, dtype: float64

In [31]:
df1

          Item  Quantity  Price_Per_Unit  Total_Spent  new_price
0       Coffee       2.0             2.0          4.0        2.0
1         Cake       4.0             3.0         12.0        3.0
2       Cookie       4.0             1.0          NaN        NaN
3        Salad       2.0             5.0         10.0        5.0
4       Coffee       2.0             2.0          4.0        2.0
...        ...       ...             ...          ...        ...
9995    Coffee       2.0             2.0          4.0        2.0
9996       NaN       3.0             NaN          3.0        1.0
9997    Coffee       4.0             2.0          8.0        2.0
9998    Cookie       3.0             NaN          3.0        1.0
9999  Sandwich       3.0             4.0         12.0        4.0

[10000 rows x 5 columns]

In [32]:
df1['new_price'] = df1['new_price'].fillna(df1['Price_Per_Unit'])

In [33]:
df1['new_price']

0       2.0
1       3.0
2       1.0
3       5.0
4       2.0
       ...
9995    2.0
9996    1.0
9997    2.0
9998    1.0
9999    4.0
Name: new_price, Length: 10000, dtype: float64

In [34]:
df1['new_quantity']=df1['Total_Spent']/df1['new_price']

In [35]:
df1

          Item  Quantity  Price_Per_Unit  Total_Spent  new_price  new_quantity
0       Coffee       2.0             2.0          4.0        2.0           2.0
1         Cake       4.0             3.0         12.0        3.0           4.0
2       Cookie       4.0             1.0          NaN        1.0           NaN
3        Salad       2.0             5.0         10.0        5.0           2.0
4       Coffee       2.0             2.0          4.0        2.0           2.0
...        ...       ...             ...          ...        ...           ...
9995    Coffee       2.0             2.0          4.0        2.0           2.0
9996       NaN       3.0             NaN          3.0        1.0           3.0
9997    Coffee       4.0             2.0          8.0        2.0           4.0
9998    Cookie       3.0             NaN          3.0        1.0           3.0
9999  Sandwich       3.0             4.0         12.0        4.0           3.0

[10000 rows x 6 columns]

In [36]:
df1['new_quantity']

0       2.0
1       4.0
2       NaN
3       2.0
4       2.0
       ...
9995    2.0
9996    3.0
9997    4.0
9998    3.0
9999    3.0
Name: new_quantity, Length: 10000, dtype: float64

In [37]:
df1['new_quantity']=df1['new_quantity'].fillna(df1['Quantity'])

In [38]:
df1['new_total']=df1['new_price']*df1['new_quantity']

In [39]:
df1['new_total']=df1['new_total'].fillna(df1['Total_Spent'])

In [40]:
df2=df1.drop(columns=['Quantity','Price_Per_Unit','Total_Spent'])

In [41]:
df2

          Item  new_price  new_quantity  new_total
0       Coffee        2.0           2.0        4.0
1         Cake        3.0           4.0       12.0
2       Cookie        1.0           4.0        4.0
3        Salad        5.0           2.0       10.0
4       Coffee        2.0           2.0        4.0
...        ...        ...           ...        ...
9995    Coffee        2.0           2.0        4.0
9996       NaN        1.0           3.0        3.0
9997    Coffee        2.0           4.0        8.0
9998    Cookie        1.0           3.0        3.0
9999  Sandwich        4.0           3.0       12.0

[10000 rows x 4 columns]

In [42]:
df2.isnull().sum()

Item            333
new_price        38
new_quantity     38
new_total        40
dtype: int64

In [43]:
price_1=df2.new_price==1

In [122]:
price_1

0       False
1       False
2        True
3       False
4       False
        ...
9995    False
9996     True
9997    False
9998     True
9999    False
Name: new_price, Length: 10000, dtype: bool

In [44]:
cookie=df2.loc[price_1,['Item','new_price','new_quantity','new_total']]

In [45]:
cookie.shape

(1207, 4)

In [46]:
cookie.isnull().sum()

Item            40
new_price        0
new_quantity     2
new_total        2
dtype: int64

In [47]:
cookie.Item.unique()

array(['Cookie', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [48]:
cookie['Item'].replace(['UNKNOWN','ERROR',np.nan],'Cookie',inplace=True)

In [49]:
cookie.Item.unique()

array(['Cookie'], dtype=object)

In [50]:
cookie=cookie.dropna(subset=['new_total', 'new_quantity'],how='all')

In [51]:
cookie.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [52]:
cookie.shape

(1205, 4)

In [53]:
price_15=df2.new_price==1.5

In [54]:
tea=df2.loc[price_15,['Item','new_price','new_quantity','new_total']]

In [55]:
tea.shape

(1200, 4)

In [56]:
tea.Item.unique()

array(['ERROR', 'Tea', nan, 'UNKNOWN'], dtype=object)

In [57]:
tea['Item'].replace(['UNKNOWN','ERROR',np.nan],'Tea',inplace=True)

In [58]:
tea.Item.unique()

array(['Tea'], dtype=object)

In [59]:
tea.isnull().sum()

Item            0
new_price       0
new_quantity    1
new_total       1
dtype: int64

In [60]:
tea=tea.dropna(subset=['new_quantity','new_total'],how='all')

In [61]:
tea.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [62]:
tea.shape

(1199, 4)

In [63]:
price_2=df2.new_price==2

In [64]:
price_2=df2.loc[price_2,['Item','new_price','new_quantity','new_total']]

In [65]:
price_2.Item.unique()

array(['Coffee', nan, 'ERROR', 'UNKNOWN'], dtype=object)

In [66]:
price_2.shape

(1289, 4)

In [67]:
price_2['Item'].replace(['ERROR','UNKNOWN',np.nan],'Coffee',inplace=True)

In [68]:
price_2.Item.unique()

array(['Coffee'], dtype=object)

In [69]:
price_2.isnull().sum()

Item            0
new_price       0
new_quantity    5
new_total       5
dtype: int64

In [70]:
price_2=price_2.dropna(subset=['new_quantity','new_total'],how='all')

In [71]:
price_2.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [72]:
price_3=df2.new_price==3

In [73]:
price_3=df2.loc[price_3,['Item','new_price','new_quantity','new_total']]

In [74]:
price_3.shape

(2552, 4)

In [75]:
price_3.Item.unique()

array(['Cake', 'UNKNOWN', nan, 'Juice', 'ERROR'], dtype=object)

In [76]:
price_3['Item'].replace(['UNKNOWN','ERROR',np.nan],'Juice',inplace=True)

In [77]:
price_3.isnull().sum()

Item            0
new_price       0
new_quantity    4
new_total       4
dtype: int64

In [78]:
price_3=price_3.dropna(subset=['new_quantity','new_total'],how='all')

In [79]:
price_3.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [80]:
price_3.shape

(2548, 4)

In [81]:
price_4=df2.new_price==4

In [82]:
price_4=df2.loc[price_4,['Item','new_price','new_quantity','new_total']]

In [83]:
price_4.shape

(2444, 4)

In [84]:
price_4.Item.unique()

array(['Smoothie', 'Sandwich', nan, 'UNKNOWN', 'ERROR'], dtype=object)

In [85]:
price_4['Item'].replace(['UNKNOWN','ERROR',np.nan],'Sandwich',inplace=True)

In [86]:
price_4.Item.unique()

array(['Smoothie', 'Sandwich'], dtype=object)

In [87]:
price_4.isnull().sum()

Item            0
new_price       0
new_quantity    6
new_total       6
dtype: int64

In [88]:
price_4=price_4.dropna(subset=['new_quantity','new_total'],how='all')

In [89]:
price_4.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [90]:
price_5=df2.new_price==5

In [91]:
price_5=df2.loc[price_5,['Item','new_price','new_quantity','new_total']]

In [92]:
price_5.shape

(1270, 4)

In [93]:
price_5.Item.unique()

array(['Salad', 'UNKNOWN', 'ERROR', nan], dtype=object)

In [94]:
price_5['Item'].replace(['UNKNOWN','ERROR',np.nan],'Salad',inplace=True)

In [95]:
price_5.Item.unique()

array(['Salad'], dtype=object)

In [96]:
price_5.isnull().sum()

Item            0
new_price       0
new_quantity    2
new_total       2
dtype: int64

In [97]:
price_5=price_5.dropna(subset=['new_quantity','new_total'],how='all')

In [98]:
price_5.shape

(1268, 4)

In [99]:
price_5.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [100]:
price_null=df2.new_price.isnull()==True

In [101]:
price_null=df2.loc[price_null,['Item','new_price','new_quantity','new_total']]

In [102]:
price_null

          Item  new_price  new_quantity  new_total
65    Sandwich        NaN           3.0        NaN
629       Cake        NaN           NaN       12.0
912   Sandwich        NaN           NaN       20.0
1008       Tea        NaN           NaN        3.0
1436       Tea        NaN           NaN        6.0
1482  Smoothie        NaN           NaN       16.0
1674       Tea        NaN           2.0        NaN
1761       NaN        NaN           4.0        NaN
2229  Sandwich        NaN           2.0        NaN
2289   UNKNOWN        NaN           4.0        NaN
2330     Salad        NaN           NaN        5.0
2585       Tea        NaN           3.0        NaN
3162      Cake        NaN           3.0        NaN
3598  Smoothie        NaN           1.0        NaN
3635    Cookie        NaN           NaN        1.0
3673  Smoothie        NaN           2.0        NaN
3779   UNKNOWN        NaN           NaN       25.0
4021    Cookie        NaN           2.0        NaN
4152     ERROR        NaN           2.0        NaN
5639       Tea        NaN           NaN        6.0
5845  Smoothie        NaN           NaN        8.0
6225    Cookie        NaN           NaN        2.0
6661    Cookie        NaN           NaN        1.0
6674    Coffee        NaN           NaN        4.0
7035     Salad        NaN           5.0        NaN
7230    Cookie        NaN           2.0        NaN
7244  Sandwich        NaN           5.0        NaN
7568    Cookie        NaN           5.0        NaN
7597     ERROR        NaN           NaN        9.0
7686    Coffee        NaN           5.0        NaN
8128  Smoothie        NaN           3.0        NaN
8497  Sandwich        NaN           3.0        NaN
8669      Cake        NaN           NaN        3.0
8975       Tea        NaN           NaN        7.5
9212       Tea        NaN           1.0        NaN
9464      Cake        NaN           NaN        3.0
9819       NaN        NaN           NaN       20.0
9893     Juice        NaN           2.0        NaN

In [103]:
price_null['Item'].replace(['ERROR','UNKNOWN'],np.nan,inplace=True)

In [104]:
price_null.dropna(subset=['Item'],inplace=True)

In [105]:
price_null.shape

(32, 4)

In [106]:
def price(x):
    if x=='Cookie':
        return 1
    elif x=='Tea':
        return 1.5
    elif x=='Coffee':
        return 2
    elif x=='Cake':
        return 3
    elif x=='Juice':
        return 3
    elif x=='Smoothie':
        return 4
    elif x=='Sandwich':
        return 4
    else:
        return 5
a='Cake'
b='vignesh'
price(a)

3

In [107]:
price_null['new_price']=price_null.Item.apply(price)

In [108]:
price_null.shape

(32, 4)

In [109]:
price_null['new']=price_null['new_total']/price_null['new_price']

In [110]:
price_null

          Item  new_price  new_quantity  new_total  new
65    Sandwich        4.0           3.0        NaN  NaN
629       Cake        3.0           NaN       12.0  4.0
912   Sandwich        4.0           NaN       20.0  5.0
1008       Tea        1.5           NaN        3.0  2.0
1436       Tea        1.5           NaN        6.0  4.0
1482  Smoothie        4.0           NaN       16.0  4.0
1674       Tea        1.5           2.0        NaN  NaN
2229  Sandwich        4.0           2.0        NaN  NaN
2330     Salad        5.0           NaN        5.0  1.0
2585       Tea        1.5           3.0        NaN  NaN
3162      Cake        3.0           3.0        NaN  NaN
3598  Smoothie        4.0           1.0        NaN  NaN
3635    Cookie        1.0           NaN        1.0  1.0
3673  Smoothie        4.0           2.0        NaN  NaN
4021    Cookie        1.0           2.0        NaN  NaN
5639       Tea        1.5           NaN        6.0  4.0
5845  Smoothie        4.0           NaN        8.0  2.0
6225    Cookie        1.0           NaN        2.0  2.0
6661    Cookie        1.0           NaN        1.0  1.0
6674    Coffee        2.0           NaN        4.0  2.0
7035     Salad        5.0           5.0        NaN  NaN
7230    Cookie        1.0           2.0        NaN  NaN
7244  Sandwich        4.0           5.0        NaN  NaN
7568    Cookie        1.0           5.0        NaN  NaN
7686    Coffee        2.0           5.0        NaN  NaN
8128  Smoothie        4.0           3.0        NaN  NaN
8497  Sandwich        4.0           3.0        NaN  NaN
8669      Cake        3.0           NaN        3.0  1.0
8975       Tea        1.5           NaN        7.5  5.0
9212       Tea        1.5           1.0        NaN  NaN
9464      Cake        3.0           NaN        3.0  1.0
9893     Juice        3.0           2.0        NaN  NaN

In [111]:
price_null['new_quantity']=price_null['new'].fillna(price_null['new_quantity'])

In [112]:
price_null['new_total']=price_null['new_price']*price_null['new_quantity']

In [113]:
price_null.drop('new',axis=1,inplace=True)

In [114]:
price_null

          Item  new_price  new_quantity  new_total
65    Sandwich        4.0           3.0       12.0
629       Cake        3.0           4.0       12.0
912   Sandwich        4.0           5.0       20.0
1008       Tea        1.5           2.0        3.0
1436       Tea        1.5           4.0        6.0
1482  Smoothie        4.0           4.0       16.0
1674       Tea        1.5           2.0        3.0
2229  Sandwich        4.0           2.0        8.0
2330     Salad        5.0           1.0        5.0
2585       Tea        1.5           3.0        4.5
3162      Cake        3.0           3.0        9.0
3598  Smoothie        4.0           1.0        4.0
3635    Cookie        1.0           1.0        1.0
3673  Smoothie        4.0           2.0        8.0
4021    Cookie        1.0           2.0        2.0
5639       Tea        1.5           4.0        6.0
5845  Smoothie        4.0           2.0        8.0
6225    Cookie        1.0           2.0        2.0
6661    Cookie        1.0           1.0        1.0
6674    Coffee        2.0           2.0        4.0
7035     Salad        5.0           5.0       25.0
7230    Cookie        1.0           2.0        2.0
7244  Sandwich        4.0           5.0       20.0
7568    Cookie        1.0           5.0        5.0
7686    Coffee        2.0           5.0       10.0
8128  Smoothie        4.0           3.0       12.0
8497  Sandwich        4.0           3.0       12.0
8669      Cake        3.0           1.0        3.0
8975       Tea        1.5           5.0        7.5
9212       Tea        1.5           1.0        1.5
9464      Cake        3.0           1.0        3.0
9893     Juice        3.0           2.0        6.0

In [115]:
price_null.dtypes

Item             object
new_price       float64
new_quantity    float64
new_total       float64
dtype: object

In [116]:
final_result=cookie._append([tea,price_2,price_3,price_4,price_5,price_null],ignore_index=True)

In [117]:
final_result

        Item  new_price  new_quantity  new_total
0     Cookie        1.0           4.0        4.0
1     Cookie        1.0           5.0        5.0
2     Cookie        1.0           5.0        5.0
3     Cookie        1.0           2.0        2.0
4     Cookie        1.0           5.0        5.0
...      ...        ...           ...        ...
9969    Cake        3.0           1.0        3.0
9970     Tea        1.5           5.0        7.5
9971     Tea        1.5           1.0        1.5
9972    Cake        3.0           1.0        3.0
9973   Juice        3.0           2.0        6.0

[9974 rows x 4 columns]

In [118]:
final_result.shape

(9974, 4)

In [119]:
final_result.isnull().sum()

Item            0
new_price       0
new_quantity    0
new_total       0
dtype: int64

In [120]:
final_result.sample(10)

          Item  new_price  new_quantity  new_total
6086      Cake        3.0           3.0        9.0
2483    Coffee        2.0           2.0        4.0
9508     Salad        5.0           2.0       10.0
1273       Tea        1.5           2.0        3.0
6966  Smoothie        4.0           1.0        4.0
8251  Smoothie        4.0           3.0       12.0
2291       Tea        1.5           4.0        6.0
4949     Juice        3.0           3.0        9.0
9608     Salad        5.0           2.0       10.0
8770     Salad        5.0           3.0       15.0

In [121]:
final_result.to_csv("C:\\Users\\vignesh\\OneDrive\\Desktop\\Cafe in pandas\\Cafe_no_null.csv")

OSError: Cannot save file into a non-existent directory: 'C:\Users\vignesh\OneDrive\Desktop\Cafe in pandas'